version: '3'
services:
  app1:
    hostname: app1
    build: ./app1
    volumes:
      - ./app1:/app
    ports:
      - 3001:3001
  app2:
    hostname: app2
    build: ./app2
    volumes:
      - ./app2:/app
    ports:
      - 3002:3002
  nginx:
    hostname: nginx
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - app1
      - app2
